aliases:
  - &xcode
    language: objective-c
    script: script/cibuild "$TRAVIS_XCODE_WORKSPACE" "$TRAVIS_XCODE_SCHEME" "build-for-testing test-without-building"
    xcode_workspace: PersistDB.xcworkspace
  - &xcode10_2
    <<: *xcode
    osx_image: xcode10.2
  - &macOS
    xcode_scheme: PersistDB (macOS)
  - &iOS
    xcode_scheme: PersistDB (iOS)

os: osx

before_install:
  - brew install swiftformat
  - brew install swiftlint

branches:
  only:
    - master

matrix:
  include:
    - <<: *xcode10_2
      <<: *macOS
      name: macOS
    - <<: *xcode10_2
      <<: *iOS
      name: iOS
    - <<: *xcode10_2
      name: SwiftPM
      script: swift test
    - <<: *xcode10_2
      name: Standards
      script: ./Carthage/Checkouts/Standards/test

notifications:
  email: false
